server:
  port: 8080

amazon:
  access:
    key: ""
    secret-key: ""
  region: sa-east-1
  end-point:
    url: https://dynamodb.sa-east-1.amazonaws.com
  dynamodb:
    endpoint: https://dynamodb.sa-east-1.amazonaws.com